### ISSUE TITLE
Angular 11 update

### ISSUE THREAD

**Issue by hakimio** [mdlivingston/mat-select-filter#19]
Would be nice if the package was updated to Angular 11.
@mdlivingston can you do it or do you want me to create a PR?

**Comment by mdlivingston** [comment]
Should be good to go now 👍

**Comment by hakimio** [comment]
@mdlivingston Can you use Angular version range instead of a single version, like in the following example:
```json
"peerDependencies": {
    "@angular/common": ">=9.0.0 <13.0.0",
    "@angular/core": ">=9.0.0 <13.0.0"
  }
```

**Comment by mdlivingston** [comment]
> ```json
>  "@angular/common": ">=9.0.0 <13.0.0",
>     "@angular/core": ">=9.0.0 <13.0.0"
> ```

Sure thing
