### ISSUE TITLE
Support Angular 13?

### ISSUE THREAD

**Issue by YipingRuan** [mdlivingston/mat-select-filter#22]
@angular/common@">=9.0.0 <13.0.0" from mat-select-filter@2.3.9

**Comment by eduardo-r-web** [comment]
same problem, any solution?

**Comment by joslunpac** [comment]
same problem, any solution?

**Comment by YipingRuan** [comment]
Simply change the version limit to include 13 should work, but someone need to merge and publish to npm.

````
  "peerDependencies": {
    "@angular/common": ">=9.0.0 <13.0.0",
    "@angular/core": ">=9.0.0 <13.0.0"
  },
````

**Comment by nicjay** [comment]
@mdlivingston

**Comment by mdlivingston** [comment]
Should be good now
